### PR TITLE
track-listing in json

### LINKED ISSUE #7: Add a playlist experimentation
Add a experimentation which will display the contents of a json into a playlist kind of way.

### PR DESCRIPTION
**Pull request by akw105**
Fixes #7 
The json was invalid and needed some slight changes. 

The jQuery loops through the new json file and outputs the images, song names and links in the new music block on the page. It loads slow but that's the number of external images that are being pulled in.

### CODE REVIEW

**Comment by Monal5031** [comment]
ping @anshumanv If you could take a look too 😄

**Comment by anshumanv** [comment]
Looks neat, lemme test that locally @Monal5031

**Comment by Monal5031** [comment]
Tested it locally, awesome work @Amykw105 👍

**Review by Monal5031 — COMMENTED** [review]
LGTM 👍 , nice work. Thanks for the PR @Amykw105

**Review by Monal5031 — APPROVED** [review]

**Comment by anshumanv** [comment]
I'm unable to test this locally, can you provide a screenshot of how it looks @Monal5031 ?

**Comment by Monal5031** [comment]
screenshot-2017-10-15 screenshot

Take a look @anshumanv 
Though the look can be improved much, but lets focus on the implementation here.

**Comment by anshumanv** [comment]
Oh wow, amazing really. Mine is stuck here for some reason.
capture

**Comment by anshumanv** [comment]
But it shows up in firefox.

**Comment by anshumanv** [comment]
Not as a sidebar, but we can use it on a separate page as the total content served. Let's incorporate that after a while on a separate page.

**Comment by akw105** [comment]
Hi, just so you know, to retrieve data from a local json file it has to go through a local server - Firefox has this built in which is why it works there. For other browsers, you have to run the web page through xampp, valet or something similar.

**Comment by anshumanv** [comment]
Alright, thanks for the following up @Amykw105 👍

**Pull request merged**
